config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :coffees
  resources :orders do
    resources :reviews, only: [:new, :create, :index]
  end
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coffee.rb
class Coffee < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :orders, dependent: :destroy
  has_many :reviews, through: :orders

  validates :name, presence: true
  validates :description, presence: true
  validates :description, length: { in: 20..200 }
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :coffee
  has_many :reviews, dependent: :destroy

  validates :quantity, presence: true

  before_save :calculate_total_price

  def calculate_total_price
    self.order_value = self.quantity * self.coffee.price
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :order
  
  validates :rating, presence: true
  validates :rating, length: { in: 0..5 }
  validates :description, presence: true
  validates :description, length: { in: 20..200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :coffees
  has_many :orders
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # strong params fo rdevise is on application controller
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  #
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :phone_number, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :address, :phone_number, :photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/coffees_controller.rb
class CoffeesController < ApplicationController
  before_action :set_coffee, only: [:show, :edit, :update, :destroy]

  def index
    @coffees = policy_scope(Coffee)
    if params[:query].present?
      sql_query = " \
        coffees.name ILIKE :query \
        OR coffees.description ILIKE :query \
        OR users.first_name ILIKE :query \
        OR users.last_name ILIKE :query \
      "
      @coffees = Coffee.joins(:user).where(sql_query, query: "%#{params[:query]}%")
    else
      @coffees = Coffee.all
    end
  end

  def show
    @reviews = @coffee.reviews
  end

  def new
    @coffee = Coffee.new
    authorize @coffee
  end

  def create
    @coffee = Coffee.new(coffee_params)
    @coffee.user = current_user
    authorize @coffee
    if @coffee.save
      redirect_to coffee_path(@coffee)
    else
      render "new"
    end
  end

  def edit
  end

  def update
    @coffee.user = current_user
    if @coffee.update(coffee_params)
      redirect_to coffee_path(@coffee), notice: "Coffee successfuly updated!"
    else
      render :edit
    end
  end

  def destroy
    @coffee.destroy
    redirect_to coffees_path
  end

  private

  def set_coffee
    @coffee = Coffee.find(params[:id])
    authorize @coffee
  end

  def coffee_params
    params.require(:coffee).permit(:name, :description, :price, :photo)
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  before_action :set_order, only: [:new, :create]

  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.coffee = @coffee
    @order.user = @user
    if @order.save
      redirect_to @order, notice: "We have successfully placed your order!"
      # this might be something else
    else
      render :new
    end
  end

  private

  def set_order
    @user = User.find(params[:user_id])
    @coffee = Coffee.find(params[:coffee_id])
  end

  def order_params
    params.require(:order).permit(:quantity, :order_value)
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_user.orders
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    authorize @order
    @order.user_id = current_user.id

    if @order.save
      redirect_to orders_path, notice: "We have successfully placed your order!"
    else
      render :new
    end
  end
  
  def edit
  end

  private

  def order_params
    params.require(:order).permit(:quantity, :coffee_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @users = User.all

    @markers = @users.geocoded.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { user: user }),
        image_url: helpers.asset_url('coffeebean.svg')
      }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
    authorize @review
    @order = Order.find(params[:order_id])
  end

  def create
    @review = Review.new(review_params)
    authorize @review
    @order = Order.find(params[:order_id])
    @review.order = @order
    # @review.coffee = @coffee
    # Order.quantity = @coffee
    if @review.save
      redirect_to coffee_path(@order.coffee)
    else
      render "new"
    end
 
  end

  private

  def review_params
    params.require(:review).permit(:description, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.includes(:coffees)
    @coffees = Coffee.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/coffees/edit.html.erb
<div class="c-show-container">
  <div class="c-show-portal">

<h1>Edit <%= @coffee.name %></h1>

<%= simple_form_for @coffee do |c| %>
  <%= c.input :name %>
  <%= c.input :description %>
  <%= c.input :price %>
  <%= c.submit class: "btn btn-info" %>
<% end %>

  <%= link_to "Back", coffees_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/coffees/index.html.erb
<%# <h3>coffee exchange</h3> %>
<div class="c-show-container">
  <div class="c-show-portal">
<h1>Currently available coffee:</h1>

<%= form_tag coffees_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find your perfect coffee"
  %>
  <%= submit_tag "Search", class: "btn1" %>
<% end %>

  <% @coffees.each do |c| %>
      <div class="card">
        <div class="card-img">
        <% if c.photo.attached? %>
          <%= cl_image_tag c.photo.key, height: 200, width: 300, crop: :fill %>
        <% end %>
        </div>
        <div class="card-content">
          <h3 class="card-header"><%= link_to c.name, coffee_path(c), class: "card-header" %></h3>
          <p><%= c.description %></p>
          <p>Price: $<%= c.price %></p>
          <% if policy(c).edit? %>
            <p><%= link_to "Update", edit_coffee_path(c) %></p>
          <% end %>
        </div>
      </div>
  <% end %>

  </div>
</div>

<%# <div class="card">
        <img src="../images/coffee4.jpg" alt="coffee" class="card-img">
        <div class="card-content">
          <h3 class="card-header">Coffee Name</h3>
          <p>The coffee description will go right here. <br>
            Here is where the coffee description will go.</p>
          <p class="price">$15</p>
        </div>
      </div> %>

<%# if policy(Coffee).create? %>
  <%#= link_to "Sell a coffee", new_coffee_path(), class: "btn btn-primary" %>
<%# end %>

<!-- <p><%#= link_to "Go back to the home page", root_path %></p>

app/views/coffees/new.html.erb
<div class="c-show-container">
  <div class="c-show-portal">
  <%= simple_form_for @coffee do |c| %>
    <%= c.input :name %>
    <%= c.input :description %>
    <%= c.input :price %>
    <%= c.input :photo, as: :file %>
    <%= c.submit class: "btn btn-info" %>
  <% end %>

    <%= link_to "Back", coffees_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/coffees/show.html.erb
<div class="c-show-container">
  <div class="c-show-portal">

    <h1> <%= @coffee.name %> </h1>
    <h2> Grown by <%= @coffee.user.first_name %> <%= @coffee.user.last_name  %> </h2>
    <p> <%= @coffee.description %> </p>

 <%# sdfb jkhf %>
    <h2>Reviews</h2>
  <% @coffee.reviews.each do |review| %>
    <div>
      <p> Made by: <%= review.order.user.first_name %></p>
      <p> <%= review.description %> </p>
      <p> rating: <%= review.rating %> </p>
    </div>
  <% end %>

    <% if @coffee.photo.attached? %>
      <%= cl_image_tag @coffee.photo.key, height: 300, width: 400, crop: :fill %>
    <% end %>

    <div class="card">
      <% if user_signed_in? && current_user != @coffee.user %>

        <%= simple_form_for Order.new do |c| %>
          <%= c.input :quantity %>
          <%= c.hidden_field :coffee_id, value: @coffee.id %>
          <%= c.submit class: "btn btn-info", data: {confirm: "Are you sure you would like to complete this purchase?"} %>
        <% end %>
      <% end %>
    </div>


    <% if policy(@coffee).destroy? %>
      <%= link_to "Edit this coffee",  edit_coffee_path(@coffee), class: "btn btn-primary"  %>
      <%= link_to "Delete this coffee", coffee_path(@coffee), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary" %>
    <% end %>

    <%= link_to "Back", coffees_path, class: "btn1" %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeMarketplace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <%= render "pages/nav" %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

  <%= render "pages/footer" %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="c-show-container">
  <div class="c-show-portal">

    <h1>Here is the list of your orders:</h1>

    <div class="card">
      <% if @orders.present? %>
        <% @orders.each do |order|  %>
          <ul>
            <p>
              Coffee: <%= order.coffee.name %>
              User: <%= order.user.first_name %>
              Date: <%= order.created_at %>
              Quantity: <%= order.quantity %>
              Value: <%= order.order_value %>
          
              <% if policy(order).create? %>
                <%if order.reviews.present? %>
                  <%= link_to "Go to coffee", coffee_path(order.coffee) %>
                <% else %>
                  <%= link_to "Write a review", new_order_review_path(order) %>
                <% end %>
              <% end  %>
          
            </p>
          </ul>
        <% end  %>

      <% else %>
        <%= "I´m sorry, You have no orders done" %>
      <% end %>
    </div>

    <p><%= link_to "Go back to the home page", root_path %></p>

  </div>
</div>

app/views/pages/_footer.html.erb
   <footer>
      <%= link_to "View coffees", coffees_path %>
      <%= link_to "View users", users_path %>
      <%= link_to "View orders", orders_path %>
      <%= link_to "View / edit profile", edit_user_registration_path %>
   </footer>

app/views/pages/_info_window.html.erb
<h2><%= user.first_name %></h2>
<p><%= user.address %></p>
<p><%= user.phone_number %></p>

app/views/pages/_nav.html.erb
    <nav>
    <a href="https://coffee-marketplace-ckt.herokuapp.com/">
      <div class='sub-nav'>
        <img src=<%= asset_path('banner_h4qgji.svg') %> alt="coffee logo" class='nav-img'> 
        <h3>coffee exchange</h3>
      </div>
    </a>

        <%= link_to "buy coffee", coffees_path %>
        <%= link_to "sell coffee", new_coffee_path %>
        <%= link_to "community", users_path %>
        
            <% if user_signed_in? %>
        <p class='colortext'> Hello <%= current_user.first_name %> <%= current_user.last_name %>! </p>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path %>
      <% end %>
    </a>
    </nav>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
  </head>
  <body>
    <main>
        <div class='coffees'>
          <div class='coffee-grid'>
               <img src=<%= asset_path("coffee1.jpg") %> alt="good coffee" class='grid-img'>
               <img src=<%= asset_path("coffee2.jpg") %> alt="good coffee" class='grid-img'>
               <img src=<%= asset_path("coffee3.jpg") %> alt="good coffee" class='grid-img'>
               <img src=<%= asset_path("coffee4.jpg") %> alt="good coffee" class='grid-img'>
               <img src=<%= asset_path("coffee5.jpg") %> alt="good coffee" class='grid-img'>
               <img src=<%= asset_path("coffee6.jpg") %> alt="good coffee" class='grid-img'>
               <img src=<%= asset_path("coffee7.jpg") %> alt="good coffee" class='grid-img'>
               <img src=<%= asset_path("coffee8.jpg") %> alt="good coffee" class='grid-img'>
               <img src=<%= asset_path("coffee9.jpg") %> alt="good coffee" class='grid-img'>
          </div>
          <p>find the most amazing artisnal coffee in the world</p>
          <%= link_to "View Coffees", coffees_path, class: 'btn1' %>

        </div>
        <div class='community'>
          <img src=<%= asset_path("grower.jpg") %> class='grower' alt="coffee grower" style='width: 100%; height: auto; object-fit: contain;'>
        </div>
    </main>
    <section class='grower-info'>
      <div>
        <img src=<%= asset_path("coffee-splash.jpg") %> alt="coffee" class='coffeesplash'>
      </div>
      <div>
        <div class='people'>
          <div class='coffee-grid'>
            <img src=<%= asset_path("cg1.jfif") %> alt="good coffee" class='grid-img2'>
            <img src=<%= asset_path("cg2.jfif") %> alt="good coffee" class='grid-img2'>
            <img src=<%= asset_path("cg3.jfif") %> alt="good coffee" class='grid-img2'>
            <img src=<%= asset_path("cg4.jfif") %> alt="good coffee" class='grid-img2'>
            <img src=<%= asset_path("cg5.jfif") %> alt="good coffee" class='grid-img2'>
            <img src=<%= asset_path("cg6.jfif") %> alt="good coffee" class='grid-img2'>
            <img src=<%= asset_path("cg7.jfif") %> alt="good coffee" class='grid-img2'>
            <img src=<%= asset_path("cg8.jfif") %> alt="good coffee" class='grid-img2'>
            <img src=<%= asset_path("cg9.jfif") %> alt="good coffee" class='grid-img2'>
          </div>
          <p>meet the amazing people who grow world class coffee</p>
          <%= link_to "Community", users_path, class: 'btn1' %>
        </div>
      </div>
    </section>

  </body>
</html>


<p>Here is where all of our coffee community members are located:</p>
<div id="map"
     style="width: 100%; height: 300px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

<%# I removed the link_to routes becuasethey are now included in the nav %>

app/views/reviews/new.html.erb
<div class="c-show-container">
  <div class="c-show-portal">

  <%= simple_form_for [@order, @review] do |f| %>
    <%= f.input :description %>
    <%= f.input :rating %>
    <%= f.submit class: "btn btn-info" %>
  <% end %>

    <%= link_to "Back", orders_path, class: "btn1" %>
    </div>
</div>

app/views/users/index.html.erb
<div class="user-container">
  <div class="user-portal">
<h1>List of current coffee sellers</h1>

<% @users.each do |u| %>
 <% if u.coffees != []  %>
   <%= u.first_name %>
   <%= u.last_name %>
   <%= u.email %>
   
     <% u.coffees.each do |coffee| %>
       <li>
        <%= coffee.name %>
        <%= link_to "See more details", coffee_path(coffee) %>
       </li>
     <% end %>
 <% end %>
<% end %>

<p><%= link_to "Go back to the home page", root_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<div class="c-show-container">
  <div class="c-show-portal">

    <h1> <%= current_user.first_name %> </h1>

      <%= link_to "Buy this coffee", new_order_path,  %>
      <%= link_to "Delete this coffee", coffee_path(@coffee), method: :delete, data: {confirm: "Are you sure?"}  %>
      <%= link_to "Back", coffees_path, class: "btn btn-primary" %>

  </div>
</div>